export const FICTIONAL_WEBSITES = 'fictional websites'
export const REAL_WEBSITES ='real websites'
export const CODING = 'coding projects'
export const APPS = 'apps'
export const VIDEOS = 'Videos'
export const MUSIC = 'Projectos musicales'
export const ARTS = 'Artes Visuales'
export const MACRO = 'Fotografia Macro'